### PR TITLE
Make macros hygienic

### PR DESCRIPTION
**Pull request by koba-e964**
This PR makes all macro invocations in macro definitions hygienic, i.e. explicitly refers to `$crate`.
(ref: https://doc.rust-lang.org/reference/macros-by-example.html#hygiene)

It's confirmed to work with kanils without explicit `extern crate`s and `#[macro_use]`s (https://github.com/frugalos/kanils/compare/tmp/remove-extern-crate). Without this change, this branch won't compile.
However, I'm not sure about whether this is exhaustive (i.e. I've really replaced all such macro invocations). 

By the way, it looks like the 1.0.0 for this crate has already been published to [crates.io](https://crates.io/crates/trackable), but the `master` branch is still on `0.2.23`. Is it a consistent state?

### CODE REVIEW

**Comment by sile** [comment]
> By the way, it looks like the 1.0.0 for this crate has already been published

Sorry, I missed pushing my local commit...
Now the master is up-to-date. Thank you for letting me know that!

**Review by sile — APPROVED** [review]
LGTM!

**Comment by sile** [comment]
BTW, I have a concern.
As you already know, the version of the `trackable` master is v1, but AFAIK `frugalos` uses v0.2 of that.
So should I backport this patch to v0.2 branch and publish v0.2.24?

**Comment by koba-e964** [comment]
I'd like to have this change backported to v0.2 and v0.2.24 published. I'd appreciate it if we could use this change right away because changing frugalos's and its depending crates' dependency to v1 takes time.
Also, if you may, I'd like to have [semver-trick](https://github.com/dtolnay/semver-trick) applied to the new version `v0.2.24`.
`frugalos` and almost all dependencies of `frugalos` use `trackable` v0.2.*, so without semver-trick we have to update every crate's dependencies simultaneously, which is a bit time-consuming.
I think I can apply semver-trick and propose a PR if it's better.

**Comment by sile** [comment]
I see. Thank you for your reply.

> I think I can apply semver-trick and propose a PR if it's better.

It would be very helpful if you could send the PR🙇 
I'll publish v0.2.24 once the PR is merged.

**Comment by koba-e964** [comment]
I'll do this. Can you create a branch for `v0.2.*`? I'll create a PR to the branch.

**Comment by sile** [comment]
Thanks!
Just created `v0.2` branch.

**Pull request merged**
